### ISSUE TITLE
medical_ts_datasets is 3 commits behind master

### ISSUE THREAD

**Issue by maresb** [BorgwardtLab/Set_Functions_for_Time_Series#2]
The changes that @ExpectationMax made in August are not reflected in the commit id of the submodule. Is this safe to update?

**Comment by ExpectationMax** [comment]
Hey maresb,

I checked the changes you mentioned. 3 buggy patients without time series observations were removed from the physionet 2019 dataset, otherwise an update is safe thus I bumped the version in the repo.

Cheers
