### ISSUE TITLE
installation problem with keras transformer

### ISSUE THREAD

**Issue by IKKIM00** [BorgwardtLab/Set_Functions_for_Time_Series#3]
Hi! 
I am trying to run quick start following your installation guide 
but having problem with installing keras-transformer with poetry
It looks like there are some version problem.
Any help to solve this problem would be so much appreciated!

Thanks for amazing job

Installing keras-transformer (0.1.dev27+g347cb21 /workspace/inkyung/Seminar/Set_Functions_for_Time_Series/repos/keras-transformer): Failed
  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/bin/pip', 'install', '--no-deps', '-U', '/workspace/inkyu
ng/Seminar/Set_Functions_for_Time_Series/repos/keras-transformer'] errored with the following return code 1, and output:
  Processing ./repos/keras-transformer
      ERROR: Command errored out with exit status 1:
       command: /root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/bin/python -c 'import sys, setuptools, tokenize; sys.
argv[0] = '"'"'/tmp/pip-req-build-h6aratez/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h6aratez/setup.py'"'"';f=getattr
(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dk1gxjae
           cwd: /tmp/pip-req-build-h6aratez/
      Complete output (28 lines):
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-req-build-h6aratez/setup.py", line 35, in <module>
          include_package_data=True,
        File "/root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/lib/python3.7/site-packages/setuptools/dist.py", line 430, in __init__
          k: v for k, v in attrs.items()
        File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/lib/python3.7/site-packages/setuptools/dist.py", line 721, in finalize_options
          ep(self)
        File "/root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/lib/python3.7/site-packages/setuptools/dist.py", line 728, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-req-build-h6aratez/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/integration.py", line 26, inversion_keyword
          dist.metadata.version = _get_version(config)
        File "/tmp/pip-req-build-h6aratez/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version
          parsed_version = _do_parse(config)
        File "/tmp/pip-req-build-h6aratez/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 142, in _do_parse
          "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
      LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-h6aratez'.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 20.2.2; however, version 20.3.3 is available.
  You should consider upgrading via the '/root/.cache/pypoetry/virtualenvs/seft-ih-2Jpha-py3.7/bin/python -m pip install --upgrade pip' command.

  at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
`

**Comment by ExpectationMax** [comment]
Hey InKyung,

thanks for the raising this issue. This can happen sometimes when there are upstream changes to how poetry treats dependencies. Can you also provide the version of poetry you are using for the install?
I'll try to have a more detailed look at your issue after the holidays.

Cheers,
Max

**Comment by IKKIM00** [comment]
![스크린샷 2020-12-22 오후 11 00 02](https://user-images.githubusercontent.com/37397258/102896260-70596280-44a9-11eb-9b75-5067bb0f03ed.png)

Thank you so much for such a quick response!

Im using poetry version 1.1.4

Merry Christmas and happy new year!

**Comment by ExpectationMax** [comment]
Hey InKyung,

sorry for the delay.
There was an issue with the version parsing in the submodule.
I updated the code such that they are installed via git instead.
It should now work :)

Feel free to reach out if there are any further issues.

Cheers,
Max
