### ISSUE TITLE
AttributeError: 'TransformerBlock' object has no attribute 'build'

### ISSUE THREAD

**Issue by Harry-zzh** [BorgwardtLab/Set_Functions_for_Time_Series#7]
When I run the TransformerModel, the AttributeError appears, and the codes are: 
https://github.com/BorgwardtLab/Set_Functions_for_Time_Series/blob/6abd69c265b719f9703902af2c6a3254b6d2a779/seft/models/transformer.py#L94-L95
And I find that TransformerBlock of keras_transformer does not have attribute 'build' actually, and I wonder how to solve it, thanks !

**Comment by Pseudomanifold** [comment]
Can you provide more details about the versions you are using here? Are you using `poetry` (or something similar) to ensure that the correct packages are being used in this project?

**Comment by Harry-zzh** [comment]
The version of keras_transformer is "0.1.dev17+gb9d4e76", and I install it according to the description of https://github.com/ExpectationMax/keras-transformer.
I use "pip install ... " to install the packages needed. My command to run the program is "python fit_model.py --dataset physionet2019 --balance --log_dir test_transformer TransformerModel".

**Comment by Pseudomanifold** [comment]
Is it possible that you installed the library from the original GitHub repository? The linked repo contains code that patches the library to support the operation that you require.

**Comment by Harry-zzh** [comment]
Yes, I used the command "git clone https://github.com/kpot/keras-transformer.git"  described in the linked repo to install keras-transformer before.
Now I use the command "git clone https://github.com/ExpectationMax/keras-transformer.git", and it works. Thanks a lot !

**Comment by Pseudomanifold** [comment]
Great to hear! @ExpectationMax: maybe it would make sense to update the installation instructions in the repo? I can open a pull request...just let me know. Closing this as resolved now.

**Comment by ExpectationMax** [comment]
Thanks for handling this Bastian! Yes, this is true we did not adapt the Readme from the forked keras-transformer repository.  I made a quick edit so this does not occur again.

Nevertheless, when installing the package as indicated in the README of this repository, it should not lead to problems, as the pyproject.toml points to the correct repository.
